spring.application.name=ecommerce
server.port=8085

# Configuración de la conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/ecommmerce
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate (Opcional pero recomendado)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#  create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Default Data
spring.datasource.data = classpath:data.sql
spring.sql.init.mode = always